"""
Secure Boot Service (Block 5.2: G2) — **Hardened Cryptographic Integrity**.

.. warning::

   This module enforces strict Phase 9 execution. It requires a valid
   `golden_manifest.json` generated by `scripts/generate_golden_manifest.py`.
   It checks both the cryptographic integrity of the files (SHA-256) and the
   integrity of the manifest itself (HMAC-SHA256) using `KERNEL_NOMAD_SECRET`.

   If any file is modified, or if the manifest is forged, the Kernel will 
   refuse to boot.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import logging
import os
from pathlib import Path

_log = logging.getLogger(__name__)

_CRITICAL_PATHS: list[str] = [
    "src/kernel.py",
    "src/modules/bayesian_engine.py",
    "src/modules/safety_interlock.py",
    "src/modules/buffer.py",
]


class SecureBoot:
    """
    **Cryptographic** Root of Trust (RoT).

    Computes SHA-256 hashes for critical kernel files and checks file presence.
    Manifest logic is tied to `golden_manifest.json` using `KERNEL_NOMAD_SECRET`.
    """

    def __init__(self, root_dir: str | Path = "."):
        self.root_dir = Path(root_dir)
        self.secret_key = os.environ.get("KERNEL_NOMAD_SECRET", "ethos_lan_dev_override_99x")
        self.manifest_path = self.root_dir / "golden_manifest.json"

    def compute_file_hash(self, relative_path: str) -> str:
        """Compute the SHA-256 hex-digest for *relative_path* under *root_dir*."""
        file_path = self.root_dir / relative_path
        if not file_path.exists():
            return "missing"

        sha256_hash = hashlib.sha256()
        with open(file_path, "rb") as f:
            for byte_block in iter(lambda: f.read(4096), b""):
                sha256_hash.update(byte_block)
        return sha256_hash.hexdigest()

    def verify_integrity(self) -> bool:
        """Run the secure-boot HMAC presence check and hash comparison."""
        _log.info("Starting Root of Trust verification...")

        if not self.manifest_path.exists():
            _log.critical("CRITICAL FAILURE: golden_manifest.json is missing! Secure boot aborted.")
            return False

        try:
            with open(self.manifest_path, "r", encoding="utf-8") as f:
                manifest_doc = json.load(f)
        except Exception as e:
            _log.critical("CRITICAL FAILURE: Invalid golden_manifest.json format! %s", e)
            return False

        signature = manifest_doc.get("signature", "")
        payload = manifest_doc.get("files", {})

        # Verify HMAC sealing
        payload_str = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        expected_sig = hmac.new(
            self.secret_key.encode("utf-8"),
            payload_str.encode("utf-8"),
            hashlib.sha256
        ).hexdigest()

        if not hmac.compare_digest(signature, expected_sig):
            _log.critical("INTEGRITY BREACH DETECTED: Manifest HMAC mismatch! The golden_manifest has been tampered with or the KERNEL_NOMAD_SECRET is invalid.")
            return False

        _log.info("Manifest signature sealed and verified. Checking payload...")

        # Verify critical files against signed payload
        for rel_path in _CRITICAL_PATHS:
            if rel_path not in payload:
                _log.critical("INTEGRITY BREACH DETECTED: Critical path %s missing from signed manifest!", rel_path)
                return False
                
            actual_hash = self.compute_file_hash(rel_path)
            expected_hash = payload[rel_path]
            
            if actual_hash == "missing":
                _log.critical("CRITICAL FAILURE: %s is missing!", rel_path)
                return False
                
            if actual_hash != expected_hash:
                import sys
                _log.critical("INTEGRITY BREACH DETECTED: Hash mismatch for %s. (Expected %s, got %s)", rel_path, expected_hash, actual_hash)
                
                # Immediate safety lockout if core ethics files are tampered (Block 5.2 execution stop)
                # Raising SystemExit ensures we drop out of async event loops safely but aggressively
                sys.exit(88) 
                
            _log.info("Verified [SHA-256]: %s", rel_path)

        _log.info("Integrity verified (Phase 9 Hardened). Chain of trust established successfully.")
        return True


class IntegrityError(Exception):
    """Raised when the secure boot chain is broken."""
