from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List, Deque
from collections import deque
import time


@dataclass
class TimeoutTrauma:
    """Record of a cooperative timeout or sensory crash to punish the Bayesian model."""
    source_lobe: str
    latency_ms: int
    severity: float = 1.0
    context: str = "Network Unreachable / API Timeout"

@dataclass
class SemanticState:
    """Raw, unjudged semantic interpretation from the Perceptive Lobe."""
    perception_confidence: float
    raw_prompt: str
    summary: str = ""
    scenario_summary: str = ""
    suggested_context: str = "everyday"
    signals: Dict[str, float] = field(default_factory=dict)
    candidate_actions: list[Any] = field(default_factory=list)
    visual_entities: list[str] = field(default_factory=list)
    audio_sentiment: float = 0.5
    generative_candidates: list[dict[str, Any]] = field(default_factory=list)
    sensory_latency_lag: int = 0
    timeout_trauma: Optional[TimeoutTrauma] = None
    agent_id: Optional[str] = None

@dataclass
class EthicalSentence:
    """The absolute, unshakeable boolean decision from the Limbic Lobe."""
    is_safe: bool
    social_tension_locus: float  # 0.0 to 1.0 (0=Chill, 1=Terrified)
    veto_reason: Optional[str] = None
    dao_consensus_hash: Optional[str] = None
    applied_trauma_weight: float = 0.0
    
    # Optional extended fields (V2.0 EthicalLobe / Uchi-Soto path)
    social_posture: Optional[str] = None
    morals: Optional[Dict[str, Any]] = None
@dataclass
class LimbicStageResult:
    """Consolidated result from the Limbic Lobe (Social, State, Locus)."""
    social_evaluation: Any
    internal_state: Any
    locus_evaluation: Any

@dataclass
class ExecutiveStageResult:
    """Consolidated result from the Executive Lobe."""
    clean_actions: list[Any]
    decision: Optional[Any] = None

@dataclass
class BayesianStageMetadata:
    """Metadata output from STAGE 3: Bayesian Scoring."""
    mixture_posterior_alpha: Optional[tuple[float, float, float]] = None
    feedback_consistency: Optional[str] = None
    mixture_context_key: Optional[str] = None
    hierarchical_context_key: Optional[str] = None
    applied_mixture_weights: Optional[tuple[float, float, float]] = None
    bma_win_probabilities: Optional[dict[str, float]] = None
    bma_dirichlet_alpha: Optional[tuple[float, float, float]] = None
    bma_n_samples: Optional[int] = None

@dataclass
class PerceptionStageResult:
    """Shared perception stage output for chat/natural entrypoints."""
    tier: Any
    premise_advisory: Any # PremiseAdvisory
    reality_verification: Any # RealityVerificationAssessment
    perception: Any # LLMPerception
    vitality: Any # VitalityAssessment
    multimodal_trust: Any # MultimodalAssessment
    epistemic_dissonance: Any # EpistemicDissonanceAssessment
    signals: dict[str, float]
    support_buffer: dict[str, Any]
    limbic_profile: dict[str, Any]
    temporal_context: Any # TemporalContext
    perception_confidence: Any # PerceptionConfidenceEnvelope
    malabs_result: Optional[Any] = None # AbsoluteEvilResult

# ═══ MODULE 9: SENSORY FUSION & LIMBIC TENSION ═══

@dataclass
class SensoryEpisode:
    """
    Unified sensory event from Vision/Audio/Touch fusion.
    Generated by VisionContinuousDaemon at 5Hz polling rate.
    Absorbed into kernel's sensory buffer for Perceptive Lobe processing.
    """
    timestamp: float = field(default_factory=time.time)
    episode_id: str = ""  # Unique identifier for this episode
    origin: str = "vision" # "vision", "audio", "somatic"

    # Vision data
    vision_detections: list[dict] = field(default_factory=list)  # [{"class": "person", "confidence": 0.95, "bbox": [...]}, ...]
    vision_entities: list[str] = field(default_factory=list)  # ["person", "weapon", ...]
    vision_confidence: float = 0.0  # Overall vision confidence

    # Audio data (if applicable)
    audio_transcript: str = ""
    audio_sentiment: float = 0.5

    # Fused features
    threat_load: float = 0.0  # Aggregated threat assessment (0.0 = safe, 1.0 = critical)
    presence_confidence: float = 0.0  # How confident we are about user/entity presence
    signals: Dict[str, float] = field(default_factory=dict) # {"tension": 0.4}
    raw_data_ref: Optional[str] = None # Link to shared memory or file if heavy

@dataclass
class PersistentThreatTracker:
    """
    Tracks sustained threat over time for limbic escalation.
    Maintains threat_load history and duration counters.
    """
    threat_detection_time: Optional[float] = None  # When threat first detected
    max_threat_load: float = 0.0  # Peak threat level sustained
    current_threat_load: float = 0.0  # Current threat assessment
    threat_duration_sec: float = 0.0  # Seconds since threat first detected
    escalation_level: int = 0  # 0=none, 1=mild (1s), 2=medium (3s), 3=high (5s)

    def update_threat_load(self, threat_load: float, current_time: Optional[float] = None) -> None:
        """
        Update threat tracking with new threat assessment.
        Triggers escalation if threat sustained for threshold durations.
        """
        current_time = current_time or time.time()
        self.current_threat_load = threat_load
        self.max_threat_load = max(self.max_threat_load, threat_load)

        if threat_load > 0.0:
            # Threat detected
            if self.threat_detection_time is None:
                self.threat_detection_time = current_time

            # Update duration
            self.threat_duration_sec = current_time - self.threat_detection_time

            # Determine escalation level based on duration
            if self.threat_duration_sec >= 5.0:
                self.escalation_level = 3  # High
            elif self.threat_duration_sec >= 3.0:
                self.escalation_level = 2  # Medium
            elif self.threat_duration_sec >= 1.0:
                self.escalation_level = 1  # Mild
        else:
            # Threat cleared - reset tracker
            self.threat_detection_time = None
            self.threat_duration_sec = 0.0
            self.escalation_level = 0
            self.max_threat_load = 0.0

    def get_tension_modulation(self) -> float:
        """
        Calculate relational_tension modulation based on threat escalation.

        Returns:
            - 0.0: no escalation (threat_load == 0)
            - 0.05: mild (1s sustained)
            - 0.15: medium (3s sustained)
            - 0.35: high (5s+ sustained)
        """
        modulation_levels = {
            0: 0.0,
            1: 0.05,
            2: 0.15,
            3: 0.35,
        }
        return modulation_levels.get(self.escalation_level, 0.0)
