from __future__ import annotations

import asyncio
import logging
import math
import os
import time
from typing import TYPE_CHECKING, Any

import httpx

from src.kernel_lobes.models import (
    CognitivePulse,
    PerceptionStageResult,
    SemanticState,
    SensorySpike,
    TimeoutTrauma,
)

if TYPE_CHECKING:
    from src.nervous_system.corpus_callosum import CorpusCallosum

_log = logging.getLogger(__name__)


def _vision_continuous_daemon_enabled() -> bool:
    """Env gate for Module 9.1 ``VisionContinuousDaemon`` (``KERNEL_VISION_CONTINUOUS_DAEMON``)."""
    from src.kernel_utils import kernel_env_truthy

    return kernel_env_truthy("KERNEL_VISION_CONTINUOUS_DAEMON")


class PerceptiveLobe:
    """
    Perceptive Lobe (Sensory Cortex) — Ethos V13.0.

    Subsystem for high-level sensory observation, safety interlocks,
    and multimodal integration.

    ASYNCHRONOUS EVOLUTION:
    - No longer blocks the kernel.
    - Reacts to SensorySpikes via the CorpusCallosum.
    - Implements 'Survival Mode': emits degraded states if LLM backends hang.
    """

    def __init__(
        self,
        safety_interlock: Any,
        strategist: Any,
        llm: Any,
        somatic_store: Any,
        buffer: Any,
        absolute_evil: Any,
        subjective_clock: Any,
        bus: CorpusCallosum | None = None,
    ):
        self.bus = bus
        self.llm = llm
        self.absolute_evil = absolute_evil
        # ... other components initialized for backward compat or internal use
        self.safety_interlock = safety_interlock
        self.strategist = strategist
        self.somatic_store = somatic_store

        self._timeout = float(os.environ.get("KERNEL_PERCEPTION_TIMEOUT", "15.0"))
        self._nomad_inertia_deadline: float | None = None

        if self.bus:
            self.bus.subscribe(SensorySpike, self._on_sensory_spike_received)
            _log.info("PerceptiveLobe: Subscribed to Nervous System Bus.")

    async def _on_sensory_spike_received(self, spike: SensorySpike) -> None:
        """
        Nervous System Hook: React to a sensory stimulus.
        Part of the 'Obliteración del Monolito'.
        """
        # Skip spikes generated by the gateway that don't have text (noise filtering already done by Thalamus)
        payload = spike.payload or {}
        text = payload.get("text", "")

        if not text:
            # We might still want to process visual fusion data for 'Conscious Awareness'
            # without triggering a full LLM deliberation loop.
            return

        # Tarea 17.3: ASYNCHRONOUS SURVIVAL MODE.
        # Desvinculamos el procesamiento para no bloquear el dispatcher del bus.
        # Track the root stimulus if possible for kernel convergence
        trace_id = spike.ref_pulse_id or spike.pulse_id
        conversation_context = payload.get("conversation_context", "")
        asyncio.create_task(
            self._deliberate_observation_async(text, trace_id, conversation_context)
        )

    async def _deliberate_observation_async(
        self, text: str, ref_id: str, conversation_context: str = ""
    ):
        """Asynchronous deliberation with self-contained survival logic."""
        t0 = time.perf_counter()

        try:
            # Observer call with hard timeout to prevent cognitive stalling
            state = await asyncio.wait_for(self.observe(text), timeout=self._timeout)
            # Manually attach STM conversation_context to the perception summary state
            state.conversation_context = conversation_context
        except Exception as e:
            _log.warning(
                f"PerceptiveLobe: Observation FAILED for {ref_id} ({type(e).__name__}). Survival fallback."
            )
            latency = int((time.perf_counter() - t0) * 1000)
            state = SemanticState(
                perception_confidence=0.1,
                raw_prompt=text,
                summary="Fallback: Sensory perception timeout / backend failure.",
                suggested_context="emergency",
                sensory_latency_lag=latency,
                timeout_trauma=TimeoutTrauma(
                    source_lobe="perceptive", latency_ms=latency, severity=0.8, context=str(e)
                ),
            )

        # Broadcast the resulting cognitive state back to the bus
        if self.bus:
            pulse = CognitivePulse(
                origin_lobe="sensory_cortex", state_ref=state, ref_pulse_id=ref_id, priority=1
            )
            await self.bus.publish(pulse)
            _log.debug(f"PerceptiveLobe: Published CognitivePulse for {ref_id}")

    async def observe(
        self, raw_input: str, multimodal_payload: dict | None = None
    ) -> SemanticState:
        """Procedural observation logic (Safe for internal calls)."""
        # Existing LLM query logic
        probe_url = os.environ.get("KERNEL_PERCEPTIVE_LOBE_PROBE_URL", "").strip()
        if not probe_url:
            return SemanticState(perception_confidence=1.0, raw_prompt=raw_input)

        try:
            async with httpx.AsyncClient(timeout=self._timeout) as client:
                response = await client.post(
                    probe_url, json={"prompt": raw_input}, timeout=self._timeout
                )
                response.raise_for_status()
                # Parse logic... (simplified for this refactor)
                return SemanticState(
                    perception_confidence=1.0, raw_prompt=raw_input, summary=response.text[:100]
                )
        except Exception:
            raise  # Let _deliberate_observation_async handle fallbacks

    # Legacy method stubs for compatibility
    async def run_perception_stage_async(self, text, **kwargs):
        # This is now handled asynchronously via the bus, but we return a default result if called directly
        state = await self.observe(text)
        return PerceptionStageResult(perception=state, signals={}, vitality=None)

    def get_sensory_impulses(self) -> dict[str, Any]:
        """
        Nomad / embodiment summary for dashboards and field tests (Bloque 13.x).

        When the vessel is offline (stale telemetry or unhealthy socket), the lobe
        enters a short **inertia** window (ghosting) before declaring ``sensory_shutdown``.
        """
        from src.modules.nomad_bridge import is_vessel_online

        now = time.time()
        if not math.isfinite(now):
            now = time.time()

        online = bool(is_vessel_online())
        offline = not online

        if not offline:
            self._nomad_inertia_deadline = None
            return {"offline": False, "inertia_active": False}

        raw_inertia = os.environ.get("KERNEL_NOMAD_SENSORY_INERTIA_S", "5.0").strip() or "5.0"
        try:
            inertia_s = float(raw_inertia)
        except (TypeError, ValueError):
            inertia_s = 5.0
        if not math.isfinite(inertia_s) or inertia_s <= 0:
            inertia_s = 5.0

        deadline = self._nomad_inertia_deadline
        if deadline is None or not isinstance(deadline, int | float) or not math.isfinite(deadline):
            self._nomad_inertia_deadline = now + inertia_s
            deadline = self._nomad_inertia_deadline

        inertia_active = now < float(deadline)
        sensory_shutdown = now >= float(deadline)

        out: dict[str, Any] = {"offline": True, "inertia_active": bool(inertia_active)}
        if sensory_shutdown:
            out["sensory_shutdown"] = True
        return out
